[versions]
logback-classic = "1.5.19"
groovy = "4.0.27"
ivy = "2.5.3"
junit4 = "4.13.2"
spock = "2.3-groovy-4.0"
cglib = "3.3.0"
# junit5
junitJupiter = "5.13.2"

[libraries]
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
# @Grab 注解需要 apache ivy
ivy = { module = "org.apache.ivy:ivy", version.ref = "ivy" }
# Use the latest Groovy version for building this library
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovySql = { module = "org.apache.groovy:groovy-sql", version.ref = "groovy" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
#  Use the awesome Spock testing and specification framework even with Java
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
# cglib
cglib = { module = "cglib:cglib", version.ref = "cglib" }

# https://docs.gradle.org/8.14.3/userguide/java_testing.html#using_junit5
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

#[plugins]
#jmh = { id = "me.champeau.jmh", version = "0.7.1" }
