/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

group = "cn.aiclr"
version = "1.0.0-SNAPSHOT"

repositories {
    flatDir { dirs("libs") }
    mavenLocal()
    // 阿里云镜像 (推荐)
    maven { url = uri("https://maven.aliyun.com/repository/public") }
    // 阿里云Google仓库（Android项目必需）
    maven { url = uri("https://maven.aliyun.com/repository/google") }
    // 阿里云Spring仓库（Spring项目可选）
    maven { url = uri("https://maven.aliyun.com/repository/spring") }
    // 腾讯云镜像 (备选)
    maven { url = uri("https://mirrors.cloud.tencent.com/nexus/repository/maven-public") }
    // 华为云镜像 (备选)
    maven { url = uri("https://repo.huaweicloud.com/repository/maven") }
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.logback)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.11.3")

            // 获取对应的测试任务并设置并行执行
            targets.all {
                tasks.test.get().apply {
                    maxParallelForks = Runtime.getRuntime().availableProcessors() / 2
                    //开启并行测试
                    systemProperty("junit.jupiter.execution.parallel.enabled", "true")
                    //设置默认测试和模式为并行模式 不需要
//                    systemProperty("junit.jupiter.execution.parallel.mode.default", "concurrent")
                }
            }
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
